title: Sylvia Enwelikwu Henry Data Analytics Portfolio
logo: Data Analytics.jpg
description: With over two year of experience as a Data Analyst, I transform complex data, multiple-soirce data, into clear, actionable insights using advance skills in Excel, SQL, PowerBI, and staticical analysis.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
