title: Sylvia Enwelikwu Henry Data Analytics Portfolio
logo: sylviahenry84-jpg
description: With over two year of experience as a Data Analyst, I transform complex data, multiple-soirce data, into clear, actionable insights using advance skills in Excel, SQL, PowerBI, and staticical analysis. With proven experience in predictive modelling, data storytelling, and stakeholder‑focused reporting, I deliver analytical solutions that drive confident, data‑led decision‑making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
